# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones

# arr4 = np.array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
#                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
#                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
#                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
#                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
#                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
#                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
#                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
#                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
#                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])
# print(arr4)

# or

arr5 = np.zeros((10, 10), dtype=np.int32)
arr5[::2, ::2]=1
arr5[1::2, 1::2]=1

print(arr5)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [ ]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
M = np.zeros((1000, 1000), dtype=np.float64)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (1000, 1000) ndim 2 size 1000000 itemsize 8 total bytes 8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
# print(mask)
print('multiples of 3:', a[mask])
print(a)


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`

row, col = a.shape
print("Before Swap\n",a,"\n")

a[[0, -1]] = a[[row-1, 0]] # a[[0,-1]] - selecting first row and last row,,,,, a[[row-1, 0]] - selecting last row and first row

# mat[[0, 2]]  # Selects rows 0 and 2
# mat[:, [1, 3]]  # Selects columns 1 and 3

print("After Swap\n", a)


Before Swap
 [[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]] 

After Swap
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)

# b = np.arange(8)
# B = b.reshape(2,4)
# B[0,0] = 99
# print('b is modified:', b)
# #C = b.reshape(2,4).ravel()
# C = b.reshape(2,4).flatten()
# C[0] = 890

# print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [ ]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
# flatten() always returns copy, ravel() always returns view but in some cases it returns copy whenever view isnt possible

import numpy as np

arr = np.arange(27).reshape(3, 3, 3)
print("Original array:\n", arr)

arr_ravel = arr.ravel()
arr_ravel[0] = 999
print("\nAfter modifying ravel() output:")
print("Original array (affected):\n", arr)

arr = np.arange(27).reshape(3, 3, 3)

arr_flatten = arr.flatten()
arr_flatten[0] = 555
print("\nAfter modifying flatten() output:")
print("Original array (unchanged):\n", arr)


# arr=np.arange(27).reshape(3,3,3)
# print(arr)
# # arr1=arr.ravel()
# # arr1[0]=5
# # print(arr)
# arr1=arr.flatten()
# arr1[0]=5
# print(arr)



Original array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

After modifying ravel() output:
Original array (affected):
 [[[999   1   2]
  [  3   4   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]]]

After modifying flatten() output:
Original array (unchanged):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print(xy)
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


[1 3 5 2 4 6]
union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [ ]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
x, y = np.array_split(xy,2)
print(x)
print(y)


[1 3 5]
[2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [ ]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.

array1 = [0,30,45,60,90]
print('sin', np.sin(array1))
print('radians', np.deg2rad(array1))

sin [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
radians [0.         0.52359878 0.78539816 1.04719755 1.57079633]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.

row = np.arange(10)
col = np.arange(10).reshape(10,1)
mul = row*col
print(mul)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [ ]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.

random_data = np.random.default_rng(0).integers(1, 100, size=(5,4))
flat_array = random_data.flatten()
percentiles = np.percentile(flat_array, [25,50,75])
print(percentiles)


[30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [ ]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.

import numpy as np
rng = np.random.default_rng()
rolls = rng.integers(1, 7, size=100)
count_sixes = np.sum(rolls == 6)
proportion_sixes = count_sixes / 100

print("Proportion of 6s:", proportion_sixes)


Proportion of 6s: 0.13


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [80]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np
from numpy.lib import recfunctions as rfn  # recfunctions module

# Existing structured array
people = np.array([
    ('Alice', 25, 55.0),
    ('Bob',   30, 85.5)
], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

# Heights to add (matching number of rows)
heights = [160.0, 175.0]

# Add 'height' field
people_with_height = rfn.append_fields(
    people,                  # original array
    'height',                 # new field name
    heights,                  # new data
    dtypes='f4',               # data type for the new field
    usemask=False
)

print(people_with_height)
print(people_with_height['name'])
print(people_with_height['age'].mean())



[('Alice', 25, 55. , 160.) ('Bob', 30, 85.5, 175.)]
['Alice' 'Bob']
27.5


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [79]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [ ]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
import numpy as np

A = np.random.random((3,3))
b = np.random.random(3)

# Solve A·x = b
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))

# Compute eigenvalues and eigenvectors
eig_values, eig_vectors = np.linalg.eig(A)
print('Eigenvalues:', eig_values)
print('Eigenvectors:\n', eig_vectors)


A·x ≈ b? True
Eigenvalues: [ 1.28569411  0.45806001 -0.34974919]
Eigenvectors:
 [[-0.28456127 -0.89548863  0.34021368]
 [-0.39848638  0.01016285 -0.77862685]
 [-0.87191369  0.44496834  0.5272522 ]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [78]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [ ]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.

import numpy as np

# Example data array from stats section
data = np.random.rand(5, 3)  # 5 rows, 3 columns

# Step 1: Save to CSV
np.savetxt("data.csv", data, delimiter=",", fmt="%.5f")
# fmt="%.5f" means floating numbers with 5 decimal places

# Step 2: Load back from CSV
loaded_data = np.loadtxt("data.csv", delimiter=",")

# Step 3: Verify
print("Loaded equals original?", np.allclose(data, loaded_data))
print("Loaded data:\n", loaded_data)


Loaded equals original? False
Loaded data:
 [[0.22626 0.76127 0.60721]
 [0.93495 0.94999 0.46825]
 [0.86288 0.50271 0.63323]
 [0.64471 0.45904 0.88971]
 [0.98325 0.3876  0.05604]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [77]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [ ]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.

import numpy as np

# Create array of daily dates from Jan 1, 2023 to Mar 31, 2023
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')

# Difference between consecutive dates
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])

# Find how many Mondays (Monday = weekday 0)
mondays_count = np.sum(dates.astype('datetime64[D]').astype('datetime64[W]') == dates)
print("Number of Mondays:", mondays_count)


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days
Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [75]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [ ]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.

import numpy as np

# Example 2D array with NaNs
arr = np.array([
    [1,   2,   np.nan],
    [4,   np.nan, 6],
    [7,   8,   9]
], dtype=float)

print("Original array:\n", arr)

# Step 1: Compute column means while ignoring NaNs
col_means = np.nanmean(arr, axis=0)

# Step 2: Find indices where NaNs are located
nan_indices = np.where(np.isnan(arr))

# Step 3: Replace NaNs with corresponding column means
arr[nan_indices] = np.take(col_means, nan_indices[1])

print("\nArray after replacing NaNs with column means:\n", arr)


Original array:
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

Array after replacing NaNs with column means:
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [76]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [ ]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
from google.colab import files
uploaded = files.upload()
# 🖊 TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.

import numpy as np
from scipy.stats import pearsonr
from datetime import datetime
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)

if '#date' in fitness.dtype.names:
    fitness.dtype.names = tuple(['date' if name == '#date' else name for name in fitness.dtype.names])

# Convert to numpy datetime64
date_strs = [datetime.strptime(d, "%d-%m-%Y").strftime("%Y-%m-%d") for d in fitness['date']]
dates = np.array(date_strs, dtype='datetime64[D]')

# step count monthly
print("Monthly Step Counts:")
months = dates.astype('datetime64[M]')
for month in np.unique(months):
    mask = months == month
    total = fitness['step_count'][mask].sum()
    print(f"{month}: {total} steps")

sleep = np.where(fitness['hours_of_sleep'] == 500, 0, fitness['hours_of_sleep'])

# sleep vs mood
print("Sleep vs Mood Correlation:")
mood = fitness['mood']
corr, _ = pearsonr(sleep, mood)
print(f"Pearson correlation: {corr:.2f}")

# weekly average
print("Weekly Averages (Steps, Sleep):")
weeks = dates.astype('datetime64[W]')
for week in np.unique(weeks):
    mask = weeks == week
    avg_steps = fitness['step_count'][mask].mean()
    avg_sleep = sleep[mask].mean()
    print(f"{week}: Avg Steps = {avg_steps:.0f}, Avg Sleep = {avg_sleep:.1f} hrs")

Saving fitness.txt to fitness (2).txt
Monthly Step Counts:
2017-10: 79051 steps
2017-11: 103071 steps
2017-12: 89565 steps
2018-01: 10163 steps
Sleep vs Mood Correlation:
Pearson correlation: 0.21
Weekly Averages (Steps, Sleep):
2017-10-05: Avg Steps = 4742, Avg Sleep = 5.5 hrs
2017-10-12: Avg Steps = 2779, Avg Sleep = 6.1 hrs
2017-10-19: Avg Steps = 2789, Avg Sleep = 5.7 hrs
2017-10-26: Avg Steps = 2294, Avg Sleep = 6.1 hrs
2017-11-02: Avg Steps = 3568, Avg Sleep = 3.9 hrs
2017-11-09: Avg Steps = 3954, Avg Sleep = 5.9 hrs
2017-11-16: Avg Steps = 2911, Avg Sleep = 5.4 hrs
2017-11-23: Avg Steps = 3143, Avg Sleep = 6.1 hrs
2017-11-30: Avg Steps = 2913, Avg Sleep = 7.0 hrs
2017-12-07: Avg Steps = 3213, Avg Sleep = 4.1 hrs
2017-12-14: Avg Steps = 3204, Avg Sleep = 4.4 hrs
2017-12-21: Avg Steps = 2743, Avg Sleep = 4.4 hrs
2017-12-28: Avg Steps = 1857, Avg Sleep = 3.6 hrs
2018-01-04: Avg Steps = 970, Avg Sleep = 4.7 hrs


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*